### ISSUE TITLE
Unable to install PyPodio via PIP

### ISSUE THREAD

**Issue by sreenadhp** [podio/podio-py#30]
When I tried to install PyPodio via PIP, I got the following error. Is it an issue or my mistake. I am a newbie to PIP & Linux(my current OS).
The command I ran was : 
                                         sudo pip install PyPodio

/usr/bin/pip run on Tue Sep 23 17:23:39 2014
Downloading/unpacking PyPodio
  Getting page https://pypi.python.org/simple/PyPodio/
  Could not fetch URL https://pypi.python.org/simple/PyPodio/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/PyPodio/ when looking for download links for PyPodio
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for PyPodio:
- https://pypi.python.org/simple/PyPodio/
  Getting page https://pypi.python.org/simple/PyPodio/
  Could not fetch URL https://pypi.python.org/simple/PyPodio/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/PyPodio/ when looking for download links for PyPodio
  Could not find any downloads that satisfy the requirement PyPodio
  Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
  No distributions at all found for PyPodio
  Exception information:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
  DistributionNotFound: No distributions at all found for PyPodio

**Comment by gregtampa** [comment]
I have same issue and yes i have git installed.
